version: '3'

networks:
  internal:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./app:/app
      - ./config/nginx:/etc/nginx/conf.d
      - ./data/logs:/var/log/nginx/
    networks:
      - internal

  php:
    build:
      context: ./config/php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./app:/app
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
    networks:
      - internal
